name: Ejecutar UFT desde GitHub John Urquijo

on:
  workflow_dispatch:

jobs:
  run-uft:
    runs-on: self-hosted

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Crear carpeta de resultados
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "C:\UFT_GitHub_Lab\Results\ScriptPruebaAdvantage"

      - name: Ejecutar script UFT
        shell: powershell
        run: |
          & "C:\Program Files (x86)\OpenText\Functional Testing\bin\UFTBatchRunnerCMD.exe" -source "C:\UFT_GitHub_Lab\ScriptPruebaAdvantage" -result "C:\UFT_GitHub_Lab\Results\ScriptPruebaAdvantage"

      - name: Publicar resultados UFT
        uses: actions/upload-artifact@v4
        with:
          name: Resultados-UFT
          path: C:\UFT_GitHub_Lab\Results\ScriptPruebaAdvantage
 octane-integration:
    needs: run-uft
    runs-on: self-hosted

    steps:
      - name: Publicar ejecución en Octane
        uses: opentext/sdp-github-actions-integration@v25.3.0
        with:
          octaneUrl: ${{ secrets.OCTANE_URL }}
          octaneSharedSpace: ${{ secrets.OCTANE_SHARED_SPACE }}
          octaneWorkspace: ${{ secrets.OCTANE_WORKSPACE }}
          octaneClientId: ${{ secrets.OCTANE_CLIENT_ID }}
          octaneClientSecret: ${{ secrets.OCTANE_CLIENT_SECRET }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          serverBaseUrl: https://github.com/JohnUrquijo/UFT_GitHub_Lab
          pipelineNamePattern: '${workflow_name}'
