name: Ejecutar UFT desde GitHub

on:
  workflow_dispatch:

jobs:
  run-uft:
    runs-on: self-hosted

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar script UFT
        shell: powershell
        run: |
          & "C:\Program Files (x86)\OpenText\Functional Testing\bin\UFTBatchRunnerCMD.exe" -source "C:\UFT_GitHub_Lab\ScriptPruebaAdvantage"
